export const works = [
  {
    id: 'cidade-de-deus',
    title: 'Cidade de Deus',
    creator: 'Fernando Meirelles',
    medium: 'film',
    year: 2002,
    decade: '2000s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Cinema de favela',
    genre: 'Crime drama',
    style: ['Handheld camera', 'Nonlinear narrative', 'Ensemble cast'],
    themes: ['Violence', 'Coming of age', 'Urban inequality', 'Fate'],
    mood: ['Frenetic', 'Unflinching'],
    context: 'Adapted from Paulo Lins’ novel, it dramatizes three decades of organized crime in Rio de Janeiro’s Cidade de Deus favela, cast largely with nonprofessional actors from the community it depicts.',
    description: 'A kinetic, unsentimental chronicle of a boy growing up inside a drug war he never chose, told through the eyes of the one kid who got out with a camera instead of a gun.',
  },
  {
    id: 'tropicalia-ou-panis-et-circenses',
    title: 'Tropicália ou Panis et Circenses',
    creator: 'Vários Artistas (Caetano Veloso, Gilberto Gil, Os Mutantes, Gal Costa, Nara Leão, Tom Zé)',
    medium: 'music',
    year: 1968,
    decade: '1960s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Tropicália',
    genre: 'Psychedelic MPB',
    style: ['Collage', 'Genre pastiche', 'Orchestral pop'],
    themes: ['National identity', 'Modernity vs. tradition', 'Censorship', 'Political repression'],
    mood: ['Playful', 'Defiant'],
    context: 'Released under Brazil’s military dictatorship, this manifesto-album collaged bossa nova, rock, and Bahian folk into a single deliberately chaotic statement of cultural resistance.',
    description: 'A joyfully cluttered collage-record where samba, psychedelic rock, and radio jingles collide to smuggle political defiance past the censors as pure noise and color.',
  },
  {
    id: 'twin-peaks',
    title: 'Twin Peaks',
    creator: 'David Lynch & Mark Frost',
    medium: 'tv',
    year: 1990,
    decade: '1990s',
    country: 'United States',
    language: 'English',
    movement: 'American surrealism',
    genre: 'Mystery drama',
    style: ['Surrealism', 'Soap opera pastiche', 'Dream logic'],
    themes: ['Small-town secrets', 'Duality', 'Grief', 'Surrealism'],
    mood: ['Uncanny', 'Melancholic'],
    context: 'Broadcast on network television at the height of the prime-time soap, it imported art-house surrealism into a murder-mystery format American audiences thought they already understood.',
    description: 'A small logging town’s homecoming-queen murder unravels into red rooms, backwards-talking dwarves, and the quiet suggestion that evil is a place, not just a person.',
  },
  {
    id: 'grande-sertao-veredas',
    title: 'Grande Sertão: Veredas',
    creator: 'João Guimarães Rosa',
    medium: 'literature',
    year: 1956,
    decade: '1950s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism (third phase)',
    genre: 'Novel',
    style: ['Invented vocabulary', 'Stream of consciousness', 'Oral storytelling', 'Formal innovation'],
    themes: ['Good and evil', 'Memory', 'The sertão as cosmos'],
    mood: ['Hypnotic', 'Meditative'],
    context: 'Set among the jagunço outlaw-bands of Brazil’s arid interior, it reinvents Portuguese prose with neologisms and regional speech to make an entire landscape think out loud.',
    description: 'An aging former outlaw retells his life to an unseen listener in a single unbroken monologue, questioning across six hundred pages whether the devil exists — or whether he made a pact with him.',
  },
  {
    id: 'lacerda-favela-series',
    title: 'Série sobre as favelas cariocas',
    creator: 'Maureen Bisilliat',
    medium: 'photography',
    year: 1975,
    decade: '1970s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian documentary photography',
    genre: 'Social documentary',
    style: ['Black and white', 'Observational', 'Portraiture'],
    themes: ['Urban inequality', 'Everyday dignity', 'Migration'],
    mood: ['Intimate', 'Somber'],
    context: 'Working alongside Rio’s hillside communities during a period of rapid, unequal urbanization, this body of work documents daily life without the sensationalism typical of favela photojournalism at the time.',
    description: 'Quiet, dignified black-and-white portraits of hillside communities that refuse the era’s appetite for spectacle, insisting on ordinary life as the real subject.',
  },
  {
    id: 'oiticica-parangoles',
    title: 'Parangólés',
    creator: 'Hélio Oiticica',
    medium: 'visual-arts',
    year: 1964,
    decade: '1960s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Neoconcretismo / Tropicália',
    genre: 'Wearable sculpture',
    style: ['Participatory art', 'Color-field', 'Performance'],
    themes: ['Bodily experience', 'Favela culture', 'Art as event'],
    mood: ['Ecstatic', 'Liberated'],
    context: 'Developed through Oiticica’s time with samba dancers of Mangueira, these wearable cape-sculptures moved Brazilian art off the wall and onto moving bodies in the street.',
    description: 'Layered fabric capes meant to be danced in, not hung on a wall — color and structure that only become the artwork once a body sets them in motion.',
  },

  // ---------------------------------------------------------------------
  // MUSIC
  // ---------------------------------------------------------------------
  {
    id: 'chega-de-saudade',
    title: 'Chega de Saudade',
    creator: 'João Gilberto',
    medium: 'music',
    year: 1959,
    decade: '1950s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Bossa Nova',
    genre: 'Bossa nova',
    style: ['Syncopated guitar', 'Whispered vocals', 'Understatement'],
    themes: ['Longing', 'Urban Rio de Janeiro', 'Reinvention of samba'],
    mood: ['Intimate', 'Wistful'],
    context: 'João Gilberto’s debut album distilled samba’s rhythm into a hushed, off-kilter guitar pulse, founding a genre that would soon travel from Copacabana apartments to American jazz clubs.',
    description: 'A whispered, syncopated reinvention of samba that turns heartbreak into something so quiet and precise it barely raises its voice.',
  },
  {
    id: 'construcao',
    title: 'Construção',
    creator: 'Chico Buarque',
    medium: 'music',
    year: 1971,
    decade: '1970s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'MPB',
    genre: 'MPB',
    style: ['Unusual scansion', 'Proparoxytone rhymes', 'Narrative song'],
    themes: ['Labor', 'Death', 'Political repression', 'Censorship'],
    mood: ['Somber', 'Defiant'],
    context: 'Written under military censorship, the title track builds and then systematically scrambles its own verses, turning a construction worker’s fatal fall into an allegory for a country repeating its own tragedies.',
    description: 'A bricklayer falls to his death in a song that keeps rebuilding its own sentences from the same bricks, each version landing a little more wrong than the last.',
  },
  {
    id: 'da-lama-ao-caos',
    title: 'Da Lama ao Caos',
    creator: 'Chico Science & Nação Zumbi',
    medium: 'music',
    year: 1994,
    decade: '1990s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Manguebeat',
    genre: 'Mangue beat',
    style: ['Guitar riffs over maracatu percussion', 'Sampling', 'Rap-sung verses'],
    themes: ['Urban inequality', 'Regional pride', 'Modernity vs. tradition'],
    mood: ['Frenetic', 'Defiant'],
    context: 'Recorded in Recife, this album fused the Afro-Brazilian percussion of maracatu with rock, funk, and hip hop, likening the polluted mangrove swamps of the city to a satellite dish sprouting from the mud.',
    description: 'Distorted guitars collide with maracatu drums in a record that imagines Recife’s slums as an antenna picking up signals from everywhere at once.',
  },
  {
    id: 'sobrevivendo-no-inferno',
    title: 'Sobrevivendo no Inferno',
    creator: 'Racionais MC\'s',
    medium: 'music',
    year: 1997,
    decade: '1990s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Rap nacional',
    genre: 'Hip hop',
    style: ['Spoken-word verses', 'Minimal sampled beats', 'First-person testimony'],
    themes: ['Urban inequality', 'Racism', 'Violence', 'Survival'],
    mood: ['Tense', 'Unflinching'],
    context: 'Recorded independently in São Paulo’s periphery, this album became a landmark of Brazilian hip hop for narrating police violence and racism in the outskirts with a documentary bluntness radio had never allowed.',
    description: 'A grim, clear-eyed report from São Paulo’s outskirts where every verse counts the ways a Black periphery kid can be failed before noon.',
  },
  {
    id: 'kind-of-blue',
    title: 'Kind of Blue',
    creator: 'Miles Davis',
    medium: 'music',
    year: 1959,
    decade: '1950s',
    country: 'United States',
    language: 'Instrumental',
    movement: 'Modal jazz',
    genre: 'Jazz',
    style: ['Modal improvisation', 'Minimal rehearsal', 'Sparse arrangement'],
    themes: ['Improvisation', 'Restraint', 'Collective listening'],
    mood: ['Meditative', 'Cool'],
    context: 'Recorded in two sessions with a sextet given only sketched scales instead of chord charts, it replaced bebop’s density with spacious modal improvisation and became the best-selling jazz album of all time.',
    description: 'Five musicians improvising over bare scales instead of chord changes, arriving at something so unhurried it seems to invent silence as an instrument.',
  },
  {
    id: 'blue-joni-mitchell',
    title: 'Blue',
    creator: 'Joni Mitchell',
    medium: 'music',
    year: 1971,
    decade: '1970s',
    country: 'Canada',
    language: 'English',
    movement: 'Singer-songwriter confessionalism',
    genre: 'Folk',
    style: ['Open guitar tunings', 'Dulcimer', 'Diaristic lyrics'],
    themes: ['Heartbreak', 'Autonomy', 'Memory'],
    mood: ['Wistful', 'Yearning'],
    context: 'Written after a period of travel through Europe following a breakup, the album helped define the confessional singer-songwriter mode by treating diary-like candor as its own formal innovation.',
    description: 'A breakup processed in real time, sung so nakedly that the record still sounds like it was recorded with the door left open.',
  },
  {
    id: 'ok-computer',
    title: 'OK Computer',
    creator: 'Radiohead',
    medium: 'music',
    year: 1997,
    decade: '1990s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'Alternative rock',
    genre: 'Art rock',
    style: ['Layered production', 'Guitar textures', 'Fragmented lyrics'],
    themes: ['Alienation', 'Technology', 'Late capitalism'],
    mood: ['Anxious', 'Elegiac'],
    context: 'Made as consumer technology and globalized finance accelerated in the late 1990s, the album turned airport lounges, car crashes, and computerized voices into a widescreen portrait of millennial dread.',
    description: 'A concept album about feeling replaceable by your own machines, sung in falsetto over guitars that keep dissolving into static.',
  },
  {
    id: 'zombie-fela-kuti',
    title: 'Zombie',
    creator: 'Fela Kuti',
    medium: 'music',
    year: 1976,
    decade: '1970s',
    country: 'Nigeria',
    language: 'Pidgin English',
    movement: 'Afrobeat',
    genre: 'Afrobeat',
    style: ['Extended horn vamps', 'Call and response', 'Polyrhythm'],
    themes: ['Political repression', 'Satire', 'Military authoritarianism'],
    mood: ['Defiant', 'Euphoric'],
    context: 'A furious satire of the Nigerian military, comparing soldiers to mindless zombies obeying orders; the record’s popularity provoked a violent army raid on Fela’s compound the following year.',
    description: 'A fifteen-minute horn-driven taunt aimed straight at a military government, danceable enough to spread the joke to every radio in Lagos.',
  },
  {
    id: 'buena-vista-social-club',
    title: 'Buena Vista Social Club',
    creator: 'Buena Vista Social Club',
    medium: 'music',
    year: 1997,
    decade: '1990s',
    country: 'Cuba',
    language: 'Spanish',
    movement: 'Son cubano revival',
    genre: 'Son cubano',
    style: ['Acoustic ensemble', 'Call and response', 'Improvised solos'],
    themes: ['Nostalgia', 'National memory', 'Musical lineage'],
    mood: ['Warm', 'Wistful'],
    context: 'Producer Ry Cooder reunited veteran Cuban musicians, some retired for decades, to record the pre-revolutionary son and danzón repertoire of their youth, introducing it to a new global audience.',
    description: 'Musicians in their seventies and eighties reassembled to play the Havana of their youth, and the record still sounds like a room full of people remembering how to be young.',
  },
  {
    id: 'the-rite-of-spring',
    title: 'The Rite of Spring',
    creator: 'Igor Stravinsky',
    medium: 'music',
    year: 1913,
    decade: '1910s',
    country: 'Russia',
    language: 'Instrumental',
    movement: 'Musical modernism',
    genre: 'Ballet score',
    style: ['Dissonant harmony', 'Irregular meter', 'Primitivist orchestration'],
    themes: ['Ritual sacrifice', 'Pagan Russia', 'Rupture with tradition'],
    mood: ['Turbulent', 'Ecstatic'],
    context: 'Composed for Diaghilev’s Ballets Russes, its jagged rhythms and dissonant chords provoked a near-riot at its Paris premiere and are often cited as the moment classical music broke decisively with the nineteenth century.',
    description: 'A pagan sacrifice ritual scored in violent, lurching rhythms that shattered a Paris opening-night audience and rewired what an orchestra was allowed to sound like.',
  },
  {
    id: 'mississippi-goddam',
    title: 'Mississippi Goddam',
    creator: 'Nina Simone',
    medium: 'music',
    year: 1964,
    decade: '1960s',
    country: 'United States',
    language: 'English',
    movement: 'Civil rights music',
    genre: 'Jazz / Show tune',
    style: ['Show-tune tempo', 'Piano-led', 'Direct address'],
    themes: ['Racism', 'Political repression', 'Righteous anger'],
    mood: ['Defiant', 'Urgent'],
    context: 'Written within an hour of hearing about the murder of Medgar Evers and the Birmingham church bombing that killed four Black girls, Simone set her fury to a jaunty show-tune melody as a deliberate provocation.',
    description: 'A civil-rights protest song dressed up as a peppy Broadway number, the mismatch between the tune and the rage making the rage impossible to ignore.',
  },
  {
    id: 'renaissance-beyonce',
    title: 'Renaissance',
    creator: 'Beyoncé',
    medium: 'music',
    year: 2022,
    decade: '2020s',
    country: 'United States',
    language: 'English',
    movement: 'Dance and house revival',
    genre: 'Dance-pop',
    style: ['Four-on-the-floor production', 'Genre-splicing', 'Sampling'],
    themes: ['Liberation', 'Queer nightlife lineage', 'Escape'],
    mood: ['Euphoric', 'Defiant'],
    context: 'Made and released as pandemic lockdowns lifted, the album traces disco and house music back to the Black and queer ballroom scenes that invented them, framing the dancefloor as a site of collective release.',
    description: 'A club record built as a thank-you letter to the queer and Black underground that invented house music, meant to be felt in a crowd with your hands in the air.',
  },

  // ---------------------------------------------------------------------
  // FILM
  // ---------------------------------------------------------------------
  {
    id: 'deus-e-o-diabo-na-terra-do-sol',
    title: 'Deus e o Diabo na Terra do Sol',
    creator: 'Glauber Rocha',
    medium: 'film',
    year: 1964,
    decade: '1960s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Cinema Novo',
    genre: 'Political allegory',
    style: ['Sun-bleached cinematography', 'Non-naturalistic acting', 'Folk ballad narration'],
    themes: ['Drought', 'Religious fanaticism', 'Political repression', 'The sertão as cosmos'],
    mood: ['Turbulent', 'Feverish'],
    context: 'Made as a manifesto of Cinema Novo’s call for “a camera in hand and an idea in the head,” it follows a cowherd caught between a messianic preacher and a bandit-savior in the drought-stricken Northeast.',
    description: 'A cattle-hand wanders the parched sertão between a self-proclaimed saint and a folk-hero outlaw, in a raw, sun-scorched film that treats Brazil’s poorest region as sacred and cursed at once.',
  },
  {
    id: 'bacurau',
    title: 'Bacurau',
    creator: 'Kleber Mendonça Filho & Juliano Dornelles',
    medium: 'film',
    year: 2019,
    decade: '2010s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Contemporary Brazilian genre cinema',
    genre: 'Weird western / Thriller',
    style: ['Widescreen', 'Genre hybridity', 'Ensemble village cast'],
    themes: ['Political repression', 'Rural resistance', 'Colonial violence'],
    mood: ['Tense', 'Defiant'],
    context: 'Made amid rising authoritarian politics in Brazil, a fictional sertão village vanishes from digital maps just before wealthy foreign hunters arrive to treat its residents as game.',
    description: 'A small Northeastern town disappears from every map right before it needs to, and its residents turn out to be far more prepared for an invasion than anyone expects.',
  },
  {
    id: 'central-do-brasil',
    title: 'Central do Brasil',
    creator: 'Walter Salles',
    medium: 'film',
    year: 1998,
    decade: '1990s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian retomada',
    genre: 'Road drama',
    style: ['Naturalistic performance', 'Road movie structure', 'Documentary-style locations'],
    themes: ['Migration', 'Chosen family', 'The sertão as cosmos'],
    mood: ['Tender', 'Melancholic'],
    context: 'Part of the retomada, the late-1990s revival of Brazilian cinema after a state-funding collapse, it follows a cynical former teacher who writes letters for illiterate travelers in Rio’s central station.',
    description: 'A letter-writer who profits from other people’s longing for home is dragged across the Northeast by an orphaned boy, and slowly relearns what it means to belong to someone.',
  },
  {
    id: 'cabra-marcado-para-morrer',
    title: 'Cabra Marcado para Morrer',
    creator: 'Eduardo Coutinho',
    medium: 'film',
    year: 1984,
    decade: '1980s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian documentary cinema',
    genre: 'Documentary',
    style: ['Direct cinema', 'Interview-based', 'Essayistic structure'],
    themes: ['Political repression', 'Land and labor', 'Memory'],
    mood: ['Somber', 'Reflective'],
    context: 'Filming a dramatization of a peasant leader’s assassination was interrupted by the 1964 military coup and its cast scattered into hiding; Coutinho resumed the project seventeen years later, filming what had happened to them since.',
    description: 'A film about rural organizers, banned mid-shoot by a coup, quietly reassembles itself seventeen years later to ask its own cast what a stolen decade actually costs a person.',
  },
  {
    id: 'un-chien-andalou',
    title: 'Un Chien Andalou',
    creator: 'Luis Buñuel & Salvador Dalí',
    medium: 'film',
    year: 1929,
    decade: '1920s',
    country: 'France',
    language: 'French',
    movement: 'Surrealism',
    genre: 'Experimental short',
    style: ['Dream logic', 'Discontinuous editing', 'Shock imagery'],
    themes: ['Surrealism', 'Desire', 'The unconscious'],
    mood: ['Uncanny', 'Disturbing'],
    context: 'Made from the pair’s recorded dreams with a deliberate refusal of rational narrative connection between shots, it became the founding film of cinematic Surrealism.',
    description: 'Sixteen dream-logic minutes stitched together with no interest in making sense, designed to assault the eye the way its own opening image assaults an eyeball.',
  },
  {
    id: 'tokyo-story',
    title: 'Tokyo Story',
    creator: 'Yasujirō Ozu',
    medium: 'film',
    year: 1953,
    decade: '1950s',
    country: 'Japan',
    language: 'Japanese',
    movement: 'Japanese golden age cinema',
    genre: 'Family drama',
    style: ['Low camera height', 'Static framing', 'Restrained performance'],
    themes: ['Generational distance', 'Modernity vs. tradition', 'Mortality'],
    mood: ['Melancholic', 'Restrained'],
    context: 'Made during Japan’s rapid postwar urbanization, it observes an elderly couple’s visit to their grown children in Tokyo, who are too busy with modern city life to make much room for them.',
    description: 'An elderly couple travels to see their children in the city and discovers, gently and without a single raised voice, that they’ve become an inconvenience.',
  },
  {
    id: 'rashomon',
    title: 'Rashomon',
    creator: 'Akira Kurosawa',
    medium: 'film',
    year: 1950,
    decade: '1950s',
    country: 'Japan',
    language: 'Japanese',
    movement: 'Japanese golden age cinema',
    genre: 'Period drama',
    style: ['Multiple unreliable narrators', 'Expressive cinematography', 'Nonlinear narrative'],
    themes: ['Truth and memory', 'Moral ambiguity', 'Human self-interest'],
    mood: ['Tense', 'Unsettling'],
    context: 'Four witnesses give four irreconcilable accounts of the same murder in a forest, a structural device so influential that “the Rashomon effect” entered everyday language for contradictory eyewitness testimony.',
    description: 'A murder gets told four completely different ways by four people who were all there, until the truth itself starts to look like the real crime scene.',
  },
  {
    id: 'bicycle-thieves',
    title: 'Bicycle Thieves',
    creator: 'Vittorio De Sica',
    medium: 'film',
    year: 1948,
    decade: '1940s',
    country: 'Italy',
    language: 'Italian',
    movement: 'Italian neorealism',
    genre: 'Social drama',
    style: ['Nonprofessional actors', 'On-location shooting', 'Observational camera'],
    themes: ['Poverty', 'Fatherhood', 'Urban inequality'],
    mood: ['Somber', 'Unflinching'],
    context: 'Shot on real Roman streets with nonprofessional actors in the ruins of postwar poverty, it made the theft of a workman’s bicycle carry the weight of an entire economic catastrophe.',
    description: 'A father needs his bicycle to keep the only job he has, and when it’s stolen, an entire postwar city becomes the stage for one desperate, humiliating morning.',
  },
  {
    id: 'breathless-a-bout-de-souffle',
    title: 'À bout de souffle',
    creator: 'Jean-Luc Godard',
    medium: 'film',
    year: 1960,
    decade: '1960s',
    country: 'France',
    language: 'French',
    movement: 'French New Wave',
    genre: 'Crime drama',
    style: ['Jump cuts', 'Handheld camera', 'Direct address'],
    themes: ['Youth rebellion', 'Amorality', 'Cinephilia'],
    mood: ['Restless', 'Cool'],
    context: 'Shot cheaply and quickly on real Paris streets, its jump cuts and disregard for continuity editing broke with studio convention and helped launch the French New Wave.',
    description: 'A small-time car thief quotes Bogart to a girl selling newspapers on the Champs-Élysées, in a film that jump-cuts its way straight through everything cinema used to think it had to do.',
  },
  {
    id: 'touki-bouki',
    title: 'Touki Bouki',
    creator: 'Djibril Diop Mambéty',
    medium: 'film',
    year: 1973,
    decade: '1970s',
    country: 'Senegal',
    language: 'Wolof',
    movement: 'African independent cinema',
    genre: 'Experimental drama',
    style: ['Nonlinear editing', 'Surreal imagery', 'Found sound collage'],
    themes: ['Migration', 'Postcolonial identity', 'The pull of Europe'],
    mood: ['Restless', 'Feverish'],
    context: 'Made a little over a decade after Senegalese independence, it follows a young herdsman and his girlfriend scheming to flee Dakar for a fantasized Paris, fusing traditional Wolof imagery with jagged, dreamlike editing.',
    description: 'A cowherd and his lover strap a pair of longhorn skulls to a stolen motorcycle and scheme their way toward a Paris that exists mostly in their own restless heads.',
  },
  {
    id: 'the-grapes-of-wrath',
    title: 'The Grapes of Wrath',
    creator: 'John Ford',
    medium: 'film',
    year: 1940,
    decade: '1940s',
    country: 'United States',
    language: 'English',
    movement: 'Depression-era social realism',
    genre: 'Drama',
    style: ['Documentary-influenced cinematography', 'Naturalistic performance'],
    themes: ['Migration', 'Poverty', 'Land and labor'],
    mood: ['Somber', 'Defiant'],
    context: 'Adapted from Steinbeck’s novel during the tail end of the Dust Bowl migration, it follows a displaced Oklahoma farming family driven west to California in search of work that mostly isn’t there.',
    description: 'A family loses its farm to drought and debt and drives west chasing rumors of work, only to find California just as hungry as the dust they left behind.',
  },
  {
    id: 'persepolis',
    title: 'Persepolis',
    creator: 'Marjane Satrapi & Vincent Paronnaud',
    medium: 'film',
    year: 2007,
    decade: '2000s',
    country: 'France',
    language: 'French',
    movement: 'Autobiographical animation',
    genre: 'Animated drama',
    style: ['Black-and-white animation', 'Graphic novel adaptation', 'First-person narration'],
    themes: ['Coming of age', 'Political repression', 'Exile'],
    mood: ['Wry', 'Melancholic'],
    context: 'Adapted from Satrapi’s own graphic memoir, it animates her childhood during the Iranian Revolution and subsequent exile in Europe in stark, hand-drawn black and white.',
    description: 'A rebellious Iranian girl comes of age through revolution, war, and exile, drawn in bold black-and-white panels that make her stubborn humor the real survival strategy.',
  },
  {
    id: 'marte-um',
    title: 'Marte Um',
    creator: 'Gabriel Martins',
    medium: 'film',
    year: 2022,
    decade: '2020s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Contemporary Brazilian cinema',
    genre: 'Family drama',
    style: ['Intimate framing', 'Ensemble family portrait', 'Quiet naturalism'],
    themes: ['Coming of age', 'Racism', 'Aspiration'],
    mood: ['Tender', 'Hopeful'],
    context: 'Set in a working-class Black family in Belo Horizonte just after a divisive presidential election, it follows each family member’s private dream — from soccer to astrophysics — without ever losing sight of the others.',
    description: 'A Black family in Belo Horizonte each quietly chase a different dream under one roof, in a film that treats an ordinary household as its own solar system.',
  },

  // ---------------------------------------------------------------------
  // TV
  // ---------------------------------------------------------------------
  {
    id: 'avenida-brasil',
    title: 'Avenida Brasil',
    creator: 'João Emanuel Carneiro',
    medium: 'tv',
    year: 2012,
    decade: '2010s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian telenovela',
    genre: 'Telenovela',
    style: ['Serialized melodrama', 'Cliffhanger structure', 'Broad ensemble cast'],
    themes: ['Revenge', 'Class mobility', 'Urban inequality'],
    mood: ['Melodramatic', 'Suspenseful'],
    context: 'A ratings phenomenon across Brazil, it follows a girl abandoned at a landfill by her stepmother who returns years later, disguised, to infiltrate her family and take her revenge.',
    description: 'A girl dumped at a garbage landfill as a child comes back years later under a false name to slowly, deliciously destroy the woman who put her there.',
  },
  {
    id: 'cidade-dos-homens',
    title: 'Cidade dos Homens',
    creator: 'Rede Globo (developed by Fernando Meirelles and Kátia Lund)',
    medium: 'tv',
    year: 2002,
    decade: '2000s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Cinema de favela',
    genre: 'Drama series',
    style: ['Handheld camera', 'Nonprofessional cast', 'Episodic vignettes'],
    themes: ['Coming of age', 'Urban inequality', 'Friendship'],
    mood: ['Warm', 'Tense'],
    context: 'Growing out of the same favela community and creative team behind Cidade de Deus, this series followed two best friends navigating adolescence and gang violence in a Rio hillside neighborhood.',
    description: 'Two best friends grow up together on a Rio hillside where a wrong turn can mean a war, and the show keeps insisting their friendship matters more than the danger around it.',
  },
  {
    id: 'the-wire',
    title: 'The Wire',
    creator: 'David Simon',
    medium: 'tv',
    year: 2002,
    decade: '2000s',
    country: 'United States',
    language: 'English',
    movement: 'American prestige drama',
    genre: 'Crime drama',
    style: ['Novelistic serialization', 'Institutional ensemble cast', 'Journalistic realism'],
    themes: ['Urban inequality', 'Institutional failure', 'The drug trade'],
    mood: ['Somber', 'Unflinching'],
    context: 'Created by a former Baltimore crime reporter, each season widens its lens from street-level drug dealing to the police, docks, schools, and city hall, treating the whole city as a single failing system.',
    description: 'A wiretap investigation into Baltimore’s drug trade slowly widens into a portrait of every institution that failed to fix it, told with the patience of a novel instead of a police procedural.',
  },
  {
    id: 'black-mirror',
    title: 'Black Mirror',
    creator: 'Charlie Brooker',
    medium: 'tv',
    year: 2011,
    decade: '2010s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'Anthology speculative fiction',
    genre: 'Science fiction anthology',
    style: ['Standalone episodes', 'Near-future setting', 'Satire'],
    themes: ['Technology', 'Alienation', 'Surveillance'],
    mood: ['Unsettling', 'Satirical'],
    context: 'Each self-contained episode imagines a near-future where an existing piece of technology — social media ratings, dating apps, brain implants — has been pushed just one step further than we have yet dared.',
    description: 'A different near-future nightmare every episode, each one built from a piece of technology already sitting in your pocket.',
  },
  {
    id: 'chernobyl',
    title: 'Chernobyl',
    creator: 'Craig Mazin',
    medium: 'tv',
    year: 2019,
    decade: '2010s',
    country: 'United States',
    language: 'English',
    movement: 'Historical prestige miniseries',
    genre: 'Historical drama',
    style: ['Docudrama', 'Procedural pacing', 'Muted color palette'],
    themes: ['Political repression', 'Institutional failure', 'Scientific truth'],
    mood: ['Somber', 'Dread-filled'],
    context: 'Dramatizing the 1986 nuclear disaster and its cover-up, the miniseries treats the Soviet state’s reflexive denial of an unfolding catastrophe as its own kind of radiation, spreading through every level of the bureaucracy.',
    description: 'A nuclear reactor explodes, and the real horror turns out to be how long an entire state apparatus is willing to lie about it before the science forces the truth out.',
  },
  {
    id: 'fleabag',
    title: 'Fleabag',
    creator: 'Phoebe Waller-Bridge',
    medium: 'tv',
    year: 2016,
    decade: '2010s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'British tragicomedy',
    genre: 'Comedy-drama',
    style: ['Direct-to-camera address', 'Dark comedy', 'First-person narration'],
    themes: ['Grief', 'Guilt', 'Self-sabotage'],
    mood: ['Wry', 'Melancholic'],
    context: 'Adapted from Waller-Bridge’s solo stage play, it follows a grieving, self-destructive woman in London who narrates her own bad decisions straight to the camera, using comedy as a shield against a devastating secret.',
    description: 'A woman jokes straight to camera about her own worst behavior for two seasons, until the show finally lets us see the grief she’s been performing over.',
  },
  {
    id: 'breaking-bad',
    title: 'Breaking Bad',
    creator: 'Vince Gilligan',
    medium: 'tv',
    year: 2008,
    decade: '2000s',
    country: 'United States',
    language: 'English',
    movement: 'American prestige drama',
    genre: 'Crime drama',
    style: ['Visual foreshadowing', 'Slow-burn character arc', 'Desert cinematography'],
    themes: ['Pride', 'Moral decay', 'The drug trade'],
    mood: ['Tense', 'Bleak'],
    context: 'A high school chemistry teacher diagnosed with terminal cancer turns to cooking methamphetamine to provide for his family, and the show tracks, in exacting detail, how much of his humanity that decision costs him.',
    description: 'A dying chemistry teacher starts cooking meth to leave his family money, and the show spends five seasons watching pride outlast every good reason he started with.',
  },
  {
    id: 'o-auto-da-compadecida',
    title: 'O Auto da Compadecida',
    creator: 'Guel Arraes',
    medium: 'tv',
    year: 1999,
    decade: '1990s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian regional comedy',
    genre: 'Comedy miniseries',
    style: ['Folk theater roots', 'Broad comic performance', 'Episodic structure'],
    themes: ['Religious folklore', 'Trickster wit', 'Northeastern identity'],
    mood: ['Playful', 'Warm'],
    context: 'Adapted from Ariano Suassuna’s 1955 folk play, it stages the misadventures of two con men in the sertão with a cast of saints, dogs, and Death himself sitting in literal judgment at the end.',
    description: 'Two small-time hustlers scam their way across the Northeastern backlands until Death and the saints themselves show up to settle the account, in a folk comedy that treats heaven like a courtroom drama.',
  },
  {
    id: 'cosmos-a-personal-voyage',
    title: 'Cosmos: A Personal Voyage',
    creator: 'Carl Sagan',
    medium: 'tv',
    year: 1980,
    decade: '1980s',
    country: 'United States',
    language: 'English',
    movement: 'Popular science broadcasting',
    genre: 'Documentary series',
    style: ['Direct-to-camera narration', 'Studio effects', 'Historical vignettes'],
    themes: ['Scientific wonder', 'Human insignificance and significance', 'The scale of the universe'],
    mood: ['Awestruck', 'Reflective'],
    context: 'Broadcast on American public television at the height of the Cold War space race, it presented cosmology, evolution, and the history of science to a mass audience with unabashed philosophical wonder.',
    description: 'One astronomer, one soundstage built to look like the edge of the universe, and thirteen episodes spent trying to make an entire planet feel appropriately small and lucky.',
  },
  {
    id: 'planet-earth',
    title: 'Planet Earth',
    creator: 'BBC Natural History Unit',
    medium: 'tv',
    year: 2006,
    decade: '2000s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'Landmark nature documentary',
    genre: 'Nature documentary',
    style: ['High-definition cinematography', 'Aerial photography', 'Omniscient narration'],
    themes: ['The natural world', 'Ecological fragility', 'Scale'],
    mood: ['Awestruck', 'Serene'],
    context: 'Filmed over five years across every continent using then-new high-definition cameras, it set a new technical benchmark for nature documentary and closed each episode noting the habitats already vanishing as it filmed them.',
    description: 'Five years of filming across every terrain on Earth, narrated with the calm of someone determined to show you the whole planet before more of it disappears.',
  },
  {
    id: 'el-chavo-del-ocho',
    title: 'El Chavo del Ocho',
    creator: 'Roberto Gómez Bolaños',
    medium: 'tv',
    year: 1971,
    decade: '1970s',
    country: 'Mexico',
    language: 'Spanish',
    movement: 'Latin American television comedy',
    genre: 'Sitcom',
    style: ['Live studio audience', 'Physical comedy', 'Recurring catchphrases'],
    themes: ['Poverty', 'Childhood', 'Community'],
    mood: ['Playful', 'Warm'],
    context: 'Centered on an orphaned boy living in a barrel in a working-class Mexico City courtyard, the sitcom became one of the most widely syndicated television programs in Latin American history.',
    description: 'An orphan who lives in a barrel in a shared courtyard turns poverty into slapstick, and an entire continent grew up quoting his catchphrases.',
  },
  {
    id: 'squid-game',
    title: 'Squid Game',
    creator: 'Hwang Dong-hyuk',
    medium: 'tv',
    year: 2021,
    decade: '2020s',
    country: 'South Korea',
    language: 'Korean',
    movement: 'Korean streaming-era drama',
    genre: 'Survival thriller',
    style: ['Children\'s-game set pieces', 'Saturated production design', 'Ensemble cast'],
    themes: ['Debt', 'Class inequality', 'Late capitalism'],
    mood: ['Tense', 'Bleak'],
    context: 'Released globally on a streaming platform during a period of widening household debt in South Korea, it stages childhood playground games as lethal contests for cash-strapped adults competing for a fortune.',
    description: 'Hundreds of people crushed by debt sign up for a game night that turns out to be a fight to the death dressed in the bright colors of a kindergarten playground.',
  },

  // ---------------------------------------------------------------------
  // LITERATURE
  // ---------------------------------------------------------------------
  {
    id: 'macunaima',
    title: 'Macunaíma',
    creator: 'Mário de Andrade',
    medium: 'literature',
    year: 1928,
    decade: '1920s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism (Antropofagia)',
    genre: 'Novel',
    style: ['Folkloric collage', 'Invented vocabulary', 'Picaresque structure'],
    themes: ['National identity', 'Surrealism', 'Trickster wit'],
    mood: ['Playful', 'Anarchic'],
    context: 'Stitched together from Amazonian and Afro-Brazilian folklore collected across the country, this “rhapsody” follows a shapeshifting, lazy, morally slippery antihero as a deliberate anti-monument to national identity.',
    description: 'A hero “without any character” is born jet-black in the jungle, turns white by magic pool, and shapeshifts across Brazil in a folkloric fever-dream that refuses to let the nation take itself too seriously.',
  },
  {
    id: 'dom-casmurro',
    title: 'Dom Casmurro',
    creator: 'Machado de Assis',
    medium: 'literature',
    year: 1899,
    decade: '1890s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian realism',
    genre: 'Novel',
    style: ['Unreliable narration', 'Digressive prose', 'Irony'],
    themes: ['Jealousy', 'Memory', 'Truth and memory'],
    mood: ['Wry', 'Unsettling'],
    context: 'Narrated decades after the fact by a wealthy, jealous man convinced his wife betrayed him with his best friend, the novel never confirms his suspicion, turning the entire book into a case study in the unreliability of memory.',
    description: 'A man spends an entire novel building the case that his wife betrayed him, and never once proves it — leaving the reader alone with a jealousy that may have invented its own evidence.',
  },
  {
    id: 'a-hora-da-estrela',
    title: 'A Hora da Estrela',
    creator: 'Clarice Lispector',
    medium: 'literature',
    year: 1977,
    decade: '1970s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism (third phase)',
    genre: 'Novella',
    style: ['Metafiction', 'Interior monologue', 'Fragmented narration'],
    themes: ['Poverty', 'Migration', 'Existential dread'],
    mood: ['Melancholic', 'Restrained'],
    context: 'Lispector’s final novel before her death is narrated by a male author agonizing over how to tell the story of a poor, unremarkable migrant typist from the Northeast, questioning his own right to speak for her at all.',
    description: 'A struggling narrator tries and keeps failing to properly tell the story of a poor typist from the Northeast, as if her ordinary, invisible life were too enormous a thing for fiction to hold.',
  },
  {
    id: 'vidas-secas',
    title: 'Vidas Secas',
    creator: 'Graciliano Ramos',
    medium: 'literature',
    year: 1938,
    decade: '1930s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian regionalism (second phase modernism)',
    genre: 'Novel',
    style: ['Sparse prose', 'Free indirect discourse', 'Fragmented chapters'],
    themes: ['Drought', 'Migration', 'Poverty', 'Land and labor'],
    mood: ['Bleak', 'Spare'],
    context: 'Told largely through the near-wordless consciousness of a family and their dog fleeing drought across the Northeastern backlands, its stripped-down prose mirrors the barrenness of the land itself.',
    description: 'A family and their dog wander a drought-ravaged backland with almost no words between them, in prose so pared down it reads like the parched land is narrating itself.',
  },
  {
    id: 'torto-arado',
    title: 'Torto Arado',
    creator: 'Itamar Vieira Junior',
    medium: 'literature',
    year: 2019,
    decade: '2010s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Contemporary Brazilian literature',
    genre: 'Novel',
    style: ['Dual sisterly narration', 'Oral folk tradition', 'Magical realism'],
    themes: ['Land and labor', 'Racism', 'Afro-Brazilian spirituality'],
    mood: ['Somber', 'Lyrical'],
    context: 'Set among Afro-descendant sharecroppers in the Bahian interior, still bound by near-feudal land arrangements generations after abolition, it follows two sisters whose lives split after a childhood accident with a family knife.',
    description: 'Two sisters bound to the same rural plantation land their ancestors were enslaved on grow into two entirely different women, one guided by folk spirits, the other by a fight for the land itself.',
  },
  {
    id: 'one-hundred-years-of-solitude',
    title: 'Cien años de soledad',
    creator: 'Gabriel García Márquez',
    medium: 'literature',
    year: 1967,
    decade: '1960s',
    country: 'Colombia',
    language: 'Spanish',
    movement: 'Magical realism',
    genre: 'Novel',
    style: ['Magical realism', 'Circular structure', 'Multigenerational scope'],
    themes: ['National identity', 'Fate', 'Memory', 'Surrealism'],
    mood: ['Hypnotic', 'Elegiac'],
    context: 'Following seven generations of the Buendía family in the fictional town of Macondo, it treats levitating priests and years-long rainstorms with the same flat, matter-of-fact tone as a birth certificate, founding the genre later called magical realism.',
    description: 'A family founds a town, and for a hundred years ghosts, prophecies, and plagues of insomnia pass through it with the same shrug as any ordinary Tuesday.',
  },
  {
    id: 'nineteen-eighty-four',
    title: 'Nineteen Eighty-Four',
    creator: 'George Orwell',
    medium: 'literature',
    year: 1949,
    decade: '1940s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'Dystopian fiction',
    genre: 'Dystopian novel',
    style: ['Invented language (Newspeak)', 'Close third-person narration', 'Political allegory'],
    themes: ['Political repression', 'Surveillance', 'Censorship'],
    mood: ['Bleak', 'Paranoid'],
    context: 'Written in the shadow of Stalinism and wartime propaganda, it imagines a totalitarian Britain that rewrites history in real time and polices even private thought, coining terms — Big Brother, doublethink — still used to describe surveillance states today.',
    description: 'A low-level bureaucrat who rewrites history for a living starts, quietly and fatally, to want to remember the truth instead.',
  },
  {
    id: 'beloved',
    title: 'Beloved',
    creator: 'Toni Morrison',
    medium: 'literature',
    year: 1987,
    decade: '1980s',
    country: 'United States',
    language: 'English',
    movement: 'African American literature',
    genre: 'Novel',
    style: ['Nonlinear structure', 'Multiple narrators', 'Haunting as narrative device'],
    themes: ['Slavery', 'Memory', 'Trauma', 'Motherhood'],
    mood: ['Haunting', 'Elegiac'],
    context: 'Inspired by the true story of an enslaved woman who killed her own child rather than see her returned to slavery, the novel is haunted, literally, by the murdered daughter’s ghost, refusing to let the past stay past.',
    description: 'A formerly enslaved woman’s house is haunted by the daughter she killed to save her from slavery, and the ghost keeps insisting the past isn’t finished with anyone.',
  },
  {
    id: 'norwegian-wood',
    title: 'Norwegian Wood',
    creator: 'Haruki Murakami',
    medium: 'literature',
    year: 1987,
    decade: '1980s',
    country: 'Japan',
    language: 'Japanese',
    movement: 'Contemporary Japanese fiction',
    genre: 'Novel',
    style: ['First-person retrospection', 'Understated prose', 'Melancholic realism'],
    themes: ['Coming of age', 'Grief', 'Memory'],
    mood: ['Melancholic', 'Nostalgic'],
    context: 'A departure from Murakami’s usual surrealism, the novel follows a college student in late-1960s Tokyo navigating loss and desire after a friend’s suicide, becoming a generational bestseller in Japan.',
    description: 'A college student caught between two very different women keeps circling back to the friend whose suicide never really let him finish growing up.',
  },
  {
    id: 'things-fall-apart',
    title: 'Things Fall Apart',
    creator: 'Chinua Achebe',
    medium: 'literature',
    year: 1958,
    decade: '1950s',
    country: 'Nigeria',
    language: 'English',
    movement: 'Postcolonial African literature',
    genre: 'Novel',
    style: ['Igbo proverbs and oral tradition', 'Free indirect discourse', 'Tragic structure'],
    themes: ['Colonial violence', 'Modernity vs. tradition', 'Masculinity'],
    mood: ['Somber', 'Tragic'],
    context: 'Written partly as a rebuttal to European novels that portrayed Africa without interiority, it depicts a proud Igbo village leader whose rigid strength cannot survive the arrival of colonial administrators and missionaries.',
    description: 'A respected village strongman built his whole identity on never showing weakness, and it’s exactly that rigidity that breaks him when colonial rule arrives.',
  },
  {
    id: 'the-master-and-margarita',
    title: 'The Master and Margarita',
    creator: 'Mikhail Bulgakov',
    medium: 'literature',
    year: 1967,
    decade: '1960s',
    country: 'Russia',
    language: 'Russian',
    movement: 'Soviet satirical fiction',
    genre: 'Novel',
    style: ['Satire', 'Magical realism', 'Novel within a novel'],
    themes: ['Political repression', 'Surrealism', 'Good and evil', 'Censorship'],
    mood: ['Feverish', 'Satirical'],
    context: 'Written in secret under Stalin and published only decades after Bulgakov’s death in a censored magazine edition, it lets the Devil and his retinue of demons loose on officially atheist Moscow to expose the absurdity of Soviet bureaucracy.',
    description: 'The Devil turns up in officially atheist Moscow with a talking cat and a retinue of demons, and somehow bureaucratic Soviet absurdity turns out to be the more surreal part of the book.',
  },
  {
    id: 'woman-at-point-zero',
    title: 'Woman at Point Zero',
    creator: 'Nawal El Saadawi',
    medium: 'literature',
    year: 1975,
    decade: '1970s',
    country: 'Egypt',
    language: 'Arabic',
    movement: 'Arab feminist literature',
    genre: 'Novel',
    style: ['First-person testimony', 'Frame narrative', 'Direct prose'],
    themes: ['Patriarchal violence', 'Autonomy', 'Survival'],
    mood: ['Unflinching', 'Defiant'],
    context: 'Based on interviews El Saadawi conducted as a psychiatrist with a woman condemned to death for killing her abusive pimp, it lets its narrator recount, without apology, a lifetime of exploitation by men who called themselves respectable.',
    description: 'A woman on death row tells her life story to a visiting psychiatrist the night before her execution, refusing every single opportunity to ask for pity.',
  },
  {
    id: 'klara-and-the-sun',
    title: 'Klara and the Sun',
    creator: 'Kazuo Ishiguro',
    medium: 'literature',
    year: 2021,
    decade: '2020s',
    country: 'United Kingdom',
    language: 'English',
    movement: 'Contemporary speculative fiction',
    genre: 'Novel',
    style: ['Naive first-person narration', 'Restrained prose', 'Speculative setting'],
    themes: ['Technology', 'Love', 'What makes a person'],
    mood: ['Tender', 'Melancholic'],
    context: 'Narrated by a solar-powered artificial companion purchased to keep a sick child company, the novel uses its narrator’s limited, devoted understanding of the world to ask what, exactly, separates love from imitation.',
    description: 'An artificial companion watches the sun and a sick child with the same devout attention, and slowly the book makes you unsure which kind of love is supposed to be the lesser one.',
  },

  // ---------------------------------------------------------------------
  // PHOTOGRAPHY
  // ---------------------------------------------------------------------
  {
    id: 'serra-pelada',
    title: 'Serra Pelada',
    creator: 'Sebastião Salgado',
    medium: 'photography',
    year: 1986,
    decade: '1980s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian documentary photography',
    genre: 'Social documentary',
    style: ['Black and white', 'High-contrast', 'Epic scale'],
    themes: ['Land and labor', 'Migration', 'Human endurance'],
    mood: ['Epic', 'Somber'],
    context: 'Photographed at the height of a gold rush that drew tens of thousands of migrant workers to a single open-pit mine in the Amazon, the images turn a sea of mud-caked bodies climbing ladders into something almost biblical.',
    description: 'Tens of thousands of men claw gold out of a single Amazonian pit by hand, and the photographs turn their mud-streaked bodies into something between a labor strike and an ancient plague.',
  },
  {
    id: 'dulce-sudor-amargo',
    title: 'Dulce Sudor Amargo',
    creator: 'Miguel Rio Branco',
    medium: 'photography',
    year: 1985,
    decade: '1980s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian documentary photography',
    genre: 'Social documentary',
    style: ['Saturated color', 'Grainy texture', 'Fragmented composition'],
    themes: ['Urban inequality', 'Everyday dignity', 'Marginalized lives'],
    mood: ['Somber', 'Sensual'],
    context: 'Photographed in the Maciel district of Salvador, a poor neighborhood of sex workers and street life later demolished for tourism redevelopment, the series treats its subjects’ bodies with a painterly, unashamed intimacy.',
    description: 'Saturated, grainy color images of a Salvador red-light district that was later bulldozed for tourism, insisting on the beauty of a neighborhood the city wanted erased.',
  },
  {
    id: 'yanomami-andujar',
    title: 'Yanomami',
    creator: 'Claudia Andujar',
    medium: 'photography',
    year: 1976,
    decade: '1970s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian documentary photography',
    genre: 'Ethnographic documentary',
    style: ['Experimental color filters', 'Long exposure', 'Portraiture'],
    themes: ['Indigenous rights', 'Land and labor', 'Spirituality'],
    mood: ['Dreamlike', 'Intimate'],
    context: 'Living for extended periods among the Yanomami of the Amazon, Andujar combined documentary portraiture with experimental infrared film and light effects to convey the group’s cosmology, later devoting decades to activism for their land rights.',
    description: 'A photographer embeds herself with an Amazonian people for years, bending color and light until the images start to picture a whole cosmology instead of just a village.',
  },
  {
    id: 'migrant-mother',
    title: 'Migrant Mother',
    creator: 'Dorothea Lange',
    medium: 'photography',
    year: 1936,
    decade: '1930s',
    country: 'United States',
    language: 'English',
    movement: 'Farm Security Administration documentary photography',
    genre: 'Documentary portrait',
    style: ['Black and white', 'Close portraiture', 'Unposed composition'],
    themes: ['Migration', 'Poverty', 'Motherhood'],
    mood: ['Somber', 'Dignified'],
    context: 'Taken for a federal agency documenting the Dust Bowl migration, the image of a pea-picker camp mother with her children became the defining visual symbol of the Great Depression in the United States.',
    description: 'A mother stares past the camera with three children pressed against her in a migrant labor camp, and one worried, unposed glance came to stand for an entire decade of hunger.',
  },
  {
    id: 'the-americans',
    title: 'The Americans',
    creator: 'Robert Frank',
    medium: 'photography',
    year: 1958,
    decade: '1950s',
    country: 'Switzerland',
    language: 'English',
    movement: 'Postwar documentary photography',
    genre: 'Photobook',
    style: ['Grainy black and white', 'Snapshot aesthetic', 'Sequenced editing'],
    themes: ['National identity', 'Racism', 'Alienation'],
    mood: ['Restless', 'Melancholic'],
    context: 'A Swiss immigrant photographer drove across the United States on a Guggenheim fellowship, photographing jukeboxes, funerals, and segregated buses with a loose, unposed style that unsettled American critics before it reshaped the medium.',
    description: 'A Swiss outsider drives across 1950s America with a camera and comes back with a country that looks a lot lonelier, and a lot more segregated, than it wanted to admit.',
  },
  {
    id: 'images-a-la-sauvette',
    title: 'Images à la Sauvette',
    creator: 'Henri Cartier-Bresson',
    medium: 'photography',
    year: 1952,
    decade: '1950s',
    country: 'France',
    language: 'French',
    movement: 'Humanist street photography',
    genre: 'Photobook',
    style: ['Black and white', 'Candid composition', '35mm reportage'],
    themes: ['Everyday dignity', 'Chance', 'Urban life'],
    mood: ['Observant', 'Serene'],
    context: 'Its title, later translated into English as “The Decisive Moment,” gave a name to Cartier-Bresson’s theory that a photographer’s only job is to recognize the single instant when a scene’s form and meaning align.',
    description: 'A theory of photography disguised as a photobook: wait, watch, and trust that ordinary streets will hand you one perfectly composed instant if you’re patient enough to see it.',
  },
  {
    id: 'untitled-film-stills',
    title: 'Untitled Film Stills',
    creator: 'Cindy Sherman',
    medium: 'photography',
    year: 1977,
    decade: '1970s',
    country: 'United States',
    language: 'English',
    movement: 'Conceptual photography',
    genre: 'Self-portraiture',
    style: ['Staged self-portraiture', 'Black and white', 'Cinematic lighting'],
    themes: ['Identity', 'Femininity as performance', 'Media imagery'],
    mood: ['Uncanny', 'Wry'],
    context: 'Photographing herself in dozens of invented film-still scenes styled after B-movies and European art cinema, Sherman used no real films at all, exposing how instantly recognizable — and constructed — cinematic female “types” had become.',
    description: 'The artist photographs herself as dozens of familiar movie-poster women from films that were never actually made, proving how easily we can recognize a type we’ve never really seen.',
  },
  {
    id: 'the-ballad-of-sexual-dependency',
    title: 'The Ballad of Sexual Dependency',
    creator: 'Nan Goldin',
    medium: 'photography',
    year: 1986,
    decade: '1980s',
    country: 'United States',
    language: 'English',
    movement: 'Confessional documentary photography',
    genre: 'Photo diary',
    style: ['Snapshot aesthetic', 'Saturated color', 'Slideshow sequencing'],
    themes: ['Intimacy', 'Addiction', 'Queer community'],
    mood: ['Raw', 'Tender'],
    context: 'Assembled from a decade of snapshots of Goldin’s own bohemian circle of friends and lovers in downtown New York, originally shown as a slideshow set to music before becoming one of the defining photobooks about the AIDS-era demimonde.',
    description: 'A decade of unguarded snapshots of the artist’s own friends, lovers, and fights, first shown as a slideshow because no single still image could hold the whole relationship.',
  },
  {
    id: 'nuit-de-noel',
    title: 'Nuit de Noël',
    creator: 'Malick Sidibé',
    medium: 'photography',
    year: 1963,
    decade: '1960s',
    country: 'Mali',
    language: 'French',
    movement: 'West African studio photography',
    genre: 'Studio portraiture',
    style: ['Black and white', 'Studio flash', 'Patterned backdrops'],
    themes: ['Youth culture', 'National identity', 'Nightlife'],
    mood: ['Joyful', 'Cool'],
    context: 'Photographing Bamako’s dance halls and nightclubs in the years just after Malian independence, Sidibé captured a generation of young people asserting a confident, stylish modernity through music and fashion.',
    description: 'A newly independent Bamako parties all night in bell-bottoms and sharp suits, and one photographer’s flashbulb keeps catching the exact moment everyone looks unstoppably cool.',
  },
  {
    id: 'farewell-photography',
    title: 'Farewell Photography',
    creator: 'Daido Moriyama',
    medium: 'photography',
    year: 1972,
    decade: '1970s',
    country: 'Japan',
    language: 'Japanese',
    movement: 'Are-bure-boke (rough, blurred, out-of-focus)',
    genre: 'Photobook',
    style: ['High-contrast black and white', 'Blur and grain', 'Fragmented composition'],
    themes: ['Urban alienation', 'Postwar Japan', 'The medium itself'],
    mood: ['Chaotic', 'Feverish'],
    context: 'Pushing the grainy, blurred “are-bure-boke” aesthetic to a deliberate breaking point, Moriyama filled the book with torn, discarded, and technically “failed” images, questioning whether photography could still claim to capture anything at all.',
    description: 'A photobook so grainy, blurred, and torn on purpose it seems to be actively arguing with the camera about whether a photograph can ever really hold onto a city.',
  },
  {
    id: 'antlitz-der-zeit',
    title: 'Antlitz der Zeit',
    creator: 'August Sander',
    medium: 'photography',
    year: 1929,
    decade: '1920s',
    country: 'Germany',
    language: 'German',
    movement: 'Neue Sachlichkeit (New Objectivity)',
    genre: 'Documentary portraiture',
    style: ['Typological portraiture', 'Black and white', 'Formal frontal pose'],
    themes: ['National identity', 'Class', 'Social taxonomy'],
    mood: ['Restrained', 'Clinical'],
    context: 'Selected from Sander’s vast, unfinished project to photograph a cross-section of every social type in Weimar Germany, the book’s dispassionate cataloguing of bakers, soldiers, and bankers alike was later banned by the Nazi party.',
    description: 'A photographer sets out to catalogue every kind of German — the baker, the bricklayer, the banker — with such flat, dispassionate fairness that the Nazis later had the book destroyed.',
  },

  // ---------------------------------------------------------------------
  // VISUAL ARTS
  // ---------------------------------------------------------------------
  {
    id: 'abaporu',
    title: 'Abaporu',
    creator: 'Tarsila do Amaral',
    medium: 'visual-arts',
    year: 1928,
    decade: '1920s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism (Antropofagia)',
    genre: 'Painting',
    style: ['Bold color-field', 'Simplified biomorphic form', 'Tropical palette'],
    themes: ['National identity', 'The body and land', 'Cultural cannibalism'],
    mood: ['Bold', 'Enigmatic'],
    context: 'Painted as a birthday gift for the poet Oswald de Andrade, its image of an oversized-footed figure beneath a giant cactus and sun directly inspired his Manifesto Antropófago, which proposed Brazilian culture should “cannibalize” European influence on its own terms.',
    description: 'A single huge-footed figure crouches under a cactus and a sun far too big for the canvas, a small painting that ended up launching an entire manifesto about swallowing Europe whole.',
  },
  {
    id: 'bichos',
    title: 'Bichos',
    creator: 'Lygia Clark',
    medium: 'visual-arts',
    year: 1960,
    decade: '1960s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Neoconcretismo',
    genre: 'Sculpture',
    style: ['Hinged metal planes', 'Participatory art', 'Geometric abstraction'],
    themes: ['Bodily experience', 'Art as event', 'Viewer participation'],
    mood: ['Playful', 'Inviting'],
    context: 'Made of hinged aluminum plates that a viewer must physically fold and rearrange, these sculptures had no fixed final form, rejecting the passive gallery viewer central to European geometric abstraction.',
    description: 'Small hinged metal sculptures that only finish becoming art once a stranger’s hands fold them into a new shape, refusing to sit still behind glass like ordinary sculpture.',
  },
  {
    id: 'bandeirinhas-volpi',
    title: 'Bandeirinhas',
    creator: 'Alfredo Volpi',
    medium: 'visual-arts',
    year: 1955,
    decade: '1950s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism',
    genre: 'Painting',
    style: ['Flat geometric color', 'Tempera on canvas', 'Repetition and rhythm'],
    themes: ['Popular festivity', 'National identity', 'Everyday dignity'],
    mood: ['Joyful', 'Serene'],
    context: 'A self-taught house painter turned fine artist, Volpi drew his geometric compositions of small triangular flags from the June festa junina street decorations of working-class São Paulo, elevating a folk ornament into rigorous abstraction.',
    description: 'Rows of tiny painted triangle-flags, borrowed straight off the string decorations of a street festival, rearranged into a geometric abstraction as calm and orderly as a hymn.',
  },
  {
    id: 'retirantes-portinari',
    title: 'Retirantes',
    creator: 'Cândido Portinari',
    medium: 'visual-arts',
    year: 1944,
    decade: '1940s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian social realism',
    genre: 'Painting',
    style: ['Elongated figuration', 'Muted earth tones', 'Monumental composition'],
    themes: ['Drought', 'Migration', 'Poverty'],
    mood: ['Somber', 'Devastated'],
    context: 'Painted after Portinari witnessed the emaciated refugees of Northeastern drought migrations firsthand, the canvas stretches its starving figures into gaunt, elongated silhouettes that stand as a permanent indictment of the region’s neglect.',
    description: 'A family of drought refugees stretched into gaunt, skeletal shapes trudging across bare earth, painted as an accusation the country was never quite allowed to forget.',
  },
  {
    id: 'o-homem-amarelo',
    title: 'O Homem Amarelo',
    creator: 'Anita Malfatti',
    medium: 'visual-arts',
    year: 1915,
    decade: '1910s',
    country: 'Brazil',
    language: 'Portuguese',
    movement: 'Brazilian modernism (precursor)',
    genre: 'Painting',
    style: ['Expressionism', 'Distorted color', 'Bold brushwork'],
    themes: ['National identity', 'Modernity vs. tradition', 'Rupture with tradition'],
    mood: ['Turbulent', 'Defiant'],
    context: 'Exhibited in São Paulo after Malfatti studied Expressionism in Germany and the United States, its jarring color and distortion scandalized conservative critics and helped provoke the 1922 Modern Art Week that formally launched Brazilian modernism.',
    description: 'A sickly yellow-green face rendered in violent, un-academic brushstrokes so shocking to conservative São Paulo that it helped detonate the movement that reinvented Brazilian art.',
  },
  {
    id: 'guernica',
    title: 'Guernica',
    creator: 'Pablo Picasso',
    medium: 'visual-arts',
    year: 1937,
    decade: '1930s',
    country: 'Spain',
    language: 'Spanish',
    movement: 'Cubism',
    genre: 'Painting',
    style: ['Monochrome palette', 'Cubist fragmentation', 'Monumental scale'],
    themes: ['War', 'Political repression', 'Human suffering'],
    mood: ['Anguished', 'Turbulent'],
    context: 'Painted within weeks of the Nazi and Fascist bombing of the Basque town of Guernica during the Spanish Civil War, the mural-sized canvas became the twentieth century’s most reproduced statement against war.',
    description: 'A screaming horse, a dismembered soldier, and a mother wailing over a dead child, fractured into grey Cubist shards, painted as fast as Picasso could work after hearing his hometown region had been bombed flat.',
  },
  {
    id: 'the-persistence-of-memory',
    title: 'The Persistence of Memory',
    creator: 'Salvador Dalí',
    medium: 'visual-arts',
    year: 1931,
    decade: '1930s',
    country: 'Spain',
    language: 'Spanish',
    movement: 'Surrealism',
    genre: 'Painting',
    style: ['Hyperrealistic technique', 'Dream imagery', 'Small scale'],
    themes: ['Time', 'The unconscious', 'Surrealism'],
    mood: ['Uncanny', 'Dreamlike'],
    context: 'Painted using a meticulous, almost photographic technique Dalí called “hand-painted dream photographs,” its limp melting clocks draped over a barren coastal landscape became Surrealism’s single most recognizable image.',
    description: 'Soft, melting clocks drape over a dead tree and a strange fleshy creature on an empty beach, painted with such crisp technical precision that the dream feels more real than the landscape.',
  },
  {
    id: 'the-two-fridas',
    title: 'The Two Fridas',
    creator: 'Frida Kahlo',
    medium: 'visual-arts',
    year: 1939,
    decade: '1930s',
    country: 'Mexico',
    language: 'Spanish',
    movement: 'Mexican modernism / Surrealism',
    genre: 'Painting',
    style: ['Self-portraiture', 'Symbolic realism', 'Exposed anatomy'],
    themes: ['Identity', 'Heartbreak', 'Duality'],
    mood: ['Anguished', 'Defiant'],
    context: 'Painted the same year as her divorce from Diego Rivera, the canvas depicts two versions of the artist side by side, one in traditional Tehuana dress and one in European clothing, their hearts connected by a single exposed artery.',
    description: 'Two versions of the same woman sit hand in hand, their exposed hearts joined by one artery, as if heartbreak had physically split her into a Mexican self and a European one.',
  },
  {
    id: 'untitled-skull-basquiat',
    title: 'Untitled (Skull)',
    creator: 'Jean-Michel Basquiat',
    medium: 'visual-arts',
    year: 1981,
    decade: '1980s',
    country: 'United States',
    language: 'English',
    movement: 'Neo-expressionism',
    genre: 'Painting',
    style: ['Graffiti-influenced mark-making', 'Layered text and image', 'Raw figuration'],
    themes: ['Racism', 'The Black body', 'Mortality'],
    mood: ['Raw', 'Turbulent'],
    context: 'Painted while Basquiat was still transitioning from a downtown New York graffiti tagger to gallery artist, the canvas fuses anatomical diagrams, street-art scrawl, and a skull-like head into an image often read as a self-portrait.',
    description: 'A skull-like head crackles with anatomical scribbles and street-graffiti marks, a self-portrait that treats the human body like both a diagram and a warning.',
  },
  {
    id: 'infinity-mirror-rooms',
    title: 'Infinity Mirror Room',
    creator: 'Yayoi Kusama',
    medium: 'visual-arts',
    year: 1965,
    decade: '1960s',
    country: 'Japan',
    language: 'Japanese',
    movement: 'Installation art',
    genre: 'Installation',
    style: ['Mirrored environment', 'Repetition', 'Immersive scale'],
    themes: ['Infinity', 'Self-obliteration', 'Obsession'],
    mood: ['Ecstatic', 'Disorienting'],
    context: 'Built from mirrored walls and repeated polka-dotted forms, Kusama’s first mirror room let a single viewer step inside and see themselves multiplied into infinity, extending the hallucinatory dot-patterns she described experiencing since childhood.',
    description: 'Step into a mirrored room dotted with soft polka-dot sculptures and watch yourself repeat into infinity, an obsession the artist has been chasing since she was a child seeing patterns everywhere.',
  },
  {
    id: 'the-jungle-wifredo-lam',
    title: 'The Jungle',
    creator: 'Wifredo Lam',
    medium: 'visual-arts',
    year: 1943,
    decade: '1940s',
    country: 'Cuba',
    language: 'Spanish',
    movement: 'Afro-Cuban Surrealism',
    genre: 'Painting',
    style: ['Hybrid figuration', 'Dense composition', 'Masked faces'],
    themes: ['Afro-Caribbean spirituality', 'Colonial violence', 'Surrealism'],
    mood: ['Feverish', 'Turbulent'],
    context: 'Painted after Lam’s return to Cuba following years in Paris among the Surrealists, the canvas crowds masked, part-human, part-plant figures into a sugarcane thicket, fusing Afro-Cuban Santería imagery with European modernist technique.',
    description: 'Masked, half-human figures crowd into a dense sugarcane thicket, a jungle that turns out to be crowded with Afro-Cuban spirits the European art world had never had a frame for.',
  },
  {
    id: 'old-mans-cloth',
    title: "Old Man's Cloth",
    creator: 'El Anatsui',
    medium: 'visual-arts',
    year: 2003,
    decade: '2000s',
    country: 'Ghana',
    language: 'English',
    movement: 'Contemporary African sculpture',
    genre: 'Sculpture',
    style: ['Found materials', 'Metal tapestry', 'Modular assembly'],
    themes: ['Consumption and waste', 'West African trade history', 'Transformation'],
    mood: ['Sumptuous', 'Reflective'],
    context: 'Assembled from thousands of flattened liquor-bottle caps wired together by a team of assistants, the shimmering metal “cloth” evokes both traditional Ghanaian kente weaving and the history of alcohol as a colonial trade commodity.',
    description: 'Thousands of discarded liquor-bottle caps get flattened, pierced, and wired into a shimmering metal cloth that drapes like a kente robe woven from the leftovers of a trade route.',
  },
];
