// AUTO-GENERATED by scripts/sync-data.mjs — do not hand-edit.
// Run `npm run sync-data` to refresh, or `npm run sync-data -- --new` for an incremental update.
// Optional hand-curation lives in data/enrichment.json, keyed by "<source.type>:<source.sourceId>".
// This is a placeholder committed before the first real sync — see Task 7 of
// docs/superpowers/plans/2026-09-02-resonance-data-sourcing-tmdb.md.

export const works = [
  {
    id: 'placeholder-city-of-god-2002', title: 'City of God', creator: 'Fernando Meirelles',
    medium: 'film', year: 2002, decade: '2000s', country: 'Brazil', language: 'pt',
    movement: 'Brazil crime, 2000s', genre: 'Crime', style: ['Crime', 'Drama'],
    themes: ['Crime', 'poverty'], mood: ['Tense'],
    context: 'Released in 2002 in Brazil.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-1' },
  },
  {
    id: 'placeholder-city-of-men-2002', title: 'City of Men', creator: 'Unknown',
    medium: 'tv', year: 2002, decade: '2000s', country: 'Brazil', language: 'pt',
    movement: 'Brazil drama, 2000s', genre: 'Drama', style: ['Drama'],
    themes: ['Drama'], mood: ['Evocative'],
    context: 'Released in 2002 in Brazil.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-2' },
  },
  {
    id: 'placeholder-seven-samurai-1954', title: 'Seven Samurai', creator: 'Akira Kurosawa',
    medium: 'film', year: 1954, decade: '1950s', country: 'Japan', language: 'ja',
    movement: 'Japan drama, 1950s', genre: 'Drama', style: ['Drama', 'Action'],
    themes: ['Honor', 'Sacrifice'], mood: ['Epic'],
    context: 'Released in 1954 in Japan.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-3' },
  },
  {
    id: 'placeholder-breaking-bad-2008', title: 'Breaking Bad', creator: 'Vince Gilligan',
    medium: 'tv', year: 2008, decade: '2000s', country: 'United States', language: 'en',
    movement: 'United States drama, 2000s', genre: 'Drama', style: ['Drama', 'Crime'],
    themes: ['Crime', 'drug'], mood: ['Tense'],
    context: 'Released in 2008 in United States.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-4' },
  },
  {
    id: 'placeholder-amelie-2001', title: 'Amélie', creator: 'Jean-Pierre Jeunet',
    medium: 'film', year: 2001, decade: '2000s', country: 'France', language: 'fr',
    movement: 'France romance, 2000s', genre: 'Romance', style: ['Romance', 'Comedy'],
    themes: ['Whimsy'], mood: ['Playful'],
    context: 'Released in 2001 in France.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-5' },
  },
  {
    id: 'placeholder-dark-2017', title: 'Dark', creator: 'Baran bo Odar, Jantje Friese',
    medium: 'tv', year: 2017, decade: '2010s', country: 'Germany', language: 'de',
    movement: 'Germany mystery, 2010s', genre: 'Mystery', style: ['Mystery', 'Drama'],
    themes: ['Time travel'], mood: ['Unsettling'],
    context: 'Released in 2017 in Germany.',
    description: 'Placeholder entry pending the first real sync run.',
    image: null, imageCredit: null, source: { type: 'tmdb', sourceId: 'placeholder-6' },
  },
];
