import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import { DECADES } from './lib/coverage.mjs';
import { mergeWorks } from './lib/mergeWorks.mjs';
import { applyEnrichment } from './lib/applyEnrichment.mjs';
import { mapWikidataFilmToWork, mapWikidataTvToWork } from './lib/mapWikidata.mjs';
import * as wikidata from './sources/wikidata.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REAL_DATA_FILE = join(__dirname, '..', 'js', 'data.js');
const REAL_ENRICHMENT_FILE = join(__dirname, '..', 'data', 'enrichment.json');

const TARGET_PER_DECADE_MOVIE = 40;  // ~40 x 13 decades ≈ 520 movies per full run
const TARGET_PER_DECADE_TV = 25;     // ~25 x 13 decades ≈ 325 TV shows per full run
const BRAZIL_QID = 'Q155';
const RECENT_TARGET = 100;

export async function loadExistingWorks(dataFile) {
  if (!existsSync(dataFile)) return [];
  const mod = await import(`${pathToFileURL(dataFile).href}?t=${Date.now()}`);
  return mod.works || [];
}

export function loadEnrichment(enrichmentFile) {
  if (!existsSync(enrichmentFile)) return {};
  return JSON.parse(readFileSync(enrichmentFile, 'utf8'));
}

export function writeDataFile(dataFile, works) {
  const header = [
    '// AUTO-GENERATED by scripts/sync-data.mjs — do not hand-edit.',
    '// Run `npm run sync-data` to refresh, or `npm run sync-data -- --new` for an incremental update.',
    '// Optional hand-curation lives in data/enrichment.json, keyed by "<source.type>:<source.sourceId>".',
    '',
    '',
  ].join('\n');
  writeFileSync(dataFile, `${header}export const works = ${JSON.stringify(works, null, 2)};\n`, 'utf8');
}

async function fetchWikidataFull(apiKey, enrichmentMap) {
  const fresh = [];
  for (const { start, end } of DECADES) {
    try {
      const filmRows = await wikidata.queryFilms({ startYear: start, endYear: end, limit: TARGET_PER_DECADE_MOVIE });
      for (const row of filmRows) {
        fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
      }
    } catch (err) {
      console.warn(`[wikidata] film query failed for ${start}-${end}: ${err.message}`);
    }

    try {
      const tvRows = await wikidata.queryTv({ startYear: start, endYear: end, limit: TARGET_PER_DECADE_TV });
      for (const row of tvRows) {
        fresh.push(applyEnrichment(mapWikidataTvToWork(row), enrichmentMap));
      }
    } catch (err) {
      console.warn(`[wikidata] tv query failed for ${start}-${end}: ${err.message}`);
    }

    // Guarantee Brazilian representation explicitly per decade, rather than leaving it to chance —
    // this is a first-principles requirement of the product (Brazilian + international works),
    // not an incidental nice-to-have.
    try {
      const brazilFilmRows = await wikidata.queryFilms({ startYear: start, endYear: end, limit: 10, countryQid: BRAZIL_QID });
      for (const row of brazilFilmRows) {
        fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
      }
    } catch (err) {
      console.warn(`[wikidata] Brazil film query failed for ${start}-${end}: ${err.message}`);
    }
  }
  return fresh;
}

async function fetchWikidataRecent(apiKey, enrichmentMap) {
  const fresh = [];
  try {
    const filmRows = await wikidata.queryRecentFilms({ limit: RECENT_TARGET });
    for (const row of filmRows) {
      fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[wikidata] recent films failed: ${err.message}`);
  }
  try {
    const tvRows = await wikidata.queryRecentTv({ limit: RECENT_TARGET });
    for (const row of tvRows) {
      fresh.push(applyEnrichment(mapWikidataTvToWork(row), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[wikidata] recent tv failed: ${err.message}`);
  }
  return fresh;
}

export async function runSync({ dataFile, enrichmentFile, fetchFresh, apiKey, incremental }) {
  const existing = await loadExistingWorks(dataFile);
  const enrichmentMap = loadEnrichment(enrichmentFile);
  const fresh = await fetchFresh(apiKey, enrichmentMap, incremental);
  const merged = mergeWorks(existing, fresh);
  writeDataFile(dataFile, merged);
  return { existingCount: existing.length, freshCount: fresh.length, totalCount: merged.length };
}

async function main() {
  const incremental = process.argv.includes('--new');
  const result = await runSync({
    dataFile: REAL_DATA_FILE,
    enrichmentFile: REAL_ENRICHMENT_FILE,
    fetchFresh: incremental ? fetchWikidataRecent : fetchWikidataFull,
    apiKey: null, // Wikidata needs no credential — kept as a parameter only because runSync's signature (Task 5 of the prior plan) still passes it through to fetchFresh
    incremental,
  });
  console.log(`Sync complete: ${result.freshCount} fetched, ${result.totalCount} total works in js/data.js (was ${result.existingCount}).`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
