import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import { LANGUAGE_SAMPLES, DECADES } from './lib/coverage.mjs';
import { mergeWorks } from './lib/mergeWorks.mjs';
import { applyEnrichment } from './lib/applyEnrichment.mjs';
import { mapTmdbMovieToWork, mapTmdbTvToWork } from './lib/mapTmdb.mjs';
import * as tmdb from './sources/tmdb.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REAL_DATA_FILE = join(__dirname, '..', 'js', 'data.js');
const REAL_ENRICHMENT_FILE = join(__dirname, '..', 'data', 'enrichment.json');

const TARGET_PER_LANGUAGE_MOVIE = 40; // ~40 x 15 languages ≈ 600 movies per full run
const TARGET_PER_LANGUAGE_TV = 30;    // ~30 x 15 languages ≈ 450 TV shows per full run
const RECENT_TARGET = 100;

export async function loadExistingWorks(dataFile) {
  if (!existsSync(dataFile)) return [];
  const mod = await import(`${pathToFileURL(dataFile).href}?t=${Date.now()}`);
  return mod.works || [];
}

export function loadEnrichment(enrichmentFile) {
  if (!existsSync(enrichmentFile)) return {};
  return JSON.parse(readFileSync(enrichmentFile, 'utf8'));
}

export function writeDataFile(dataFile, works) {
  const header = [
    '// AUTO-GENERATED by scripts/sync-data.mjs — do not hand-edit.',
    '// Run `npm run sync-data` to refresh, or `npm run sync-data -- --new` for an incremental update.',
    '// Optional hand-curation lives in data/enrichment.json, keyed by "<source.type>:<source.sourceId>".',
    '',
    '',
  ].join('\n');
  writeFileSync(dataFile, `${header}export const works = ${JSON.stringify(works, null, 2)};\n`, 'utf8');
}

async function fetchTmdbFull(apiKey, enrichmentMap) {
  const fresh = [];
  for (const { code } of LANGUAGE_SAMPLES) {
    for (const { start, end } of DECADES) {
      try {
        const movieIds = await tmdb.discoverMovieIds(apiKey, {
          languageCode: code, startYear: start, endYear: end,
          targetCount: Math.max(1, Math.ceil(TARGET_PER_LANGUAGE_MOVIE / DECADES.length)),
        });
        for (const id of movieIds) {
          const detail = await tmdb.fetchMovieDetail(apiKey, id);
          fresh.push(applyEnrichment(mapTmdbMovieToWork(detail), enrichmentMap));
        }
      } catch (err) {
        console.warn(`[tmdb] movie discover failed for ${code} ${start}-${end}: ${err.message}`);
      }

      try {
        const tvIds = await tmdb.discoverTvIds(apiKey, {
          languageCode: code, startYear: start, endYear: end,
          targetCount: Math.max(1, Math.ceil(TARGET_PER_LANGUAGE_TV / DECADES.length)),
        });
        for (const id of tvIds) {
          const detail = await tmdb.fetchTvDetail(apiKey, id);
          fresh.push(applyEnrichment(mapTmdbTvToWork(detail), enrichmentMap));
        }
      } catch (err) {
        console.warn(`[tmdb] tv discover failed for ${code} ${start}-${end}: ${err.message}`);
      }
    }
  }
  return fresh;
}

async function fetchTmdbRecent(apiKey, enrichmentMap) {
  const fresh = [];
  try {
    const movieIds = await tmdb.fetchRecentMovieIds(apiKey, { targetCount: RECENT_TARGET });
    for (const id of movieIds) {
      const detail = await tmdb.fetchMovieDetail(apiKey, id);
      fresh.push(applyEnrichment(mapTmdbMovieToWork(detail), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[tmdb] recent movies failed: ${err.message}`);
  }
  try {
    const tvIds = await tmdb.fetchRecentTvIds(apiKey, { targetCount: RECENT_TARGET });
    for (const id of tvIds) {
      const detail = await tmdb.fetchTvDetail(apiKey, id);
      fresh.push(applyEnrichment(mapTmdbTvToWork(detail), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[tmdb] recent tv failed: ${err.message}`);
  }
  return fresh;
}

export async function runSync({ dataFile, enrichmentFile, fetchFresh, apiKey, incremental }) {
  const existing = await loadExistingWorks(dataFile);
  const enrichmentMap = loadEnrichment(enrichmentFile);
  const fresh = await fetchFresh(apiKey, enrichmentMap, incremental);
  const merged = mergeWorks(existing, fresh);
  writeDataFile(dataFile, merged);
  return { existingCount: existing.length, freshCount: fresh.length, totalCount: merged.length };
}

async function main() {
  const apiKey = process.env.TMDB_API_KEY;
  if (!apiKey) {
    console.error(
      'Missing TMDB_API_KEY environment variable.\n' +
      'Get a free key at https://www.themoviedb.org/settings/api and run:\n' +
      '  TMDB_API_KEY=your-key npm run sync-data'
    );
    process.exit(1);
  }
  const incremental = process.argv.includes('--new');
  const result = await runSync({
    dataFile: REAL_DATA_FILE,
    enrichmentFile: REAL_ENRICHMENT_FILE,
    fetchFresh: incremental ? fetchTmdbRecent : fetchTmdbFull,
    apiKey,
    incremental,
  });
  console.log(`Sync complete: ${result.freshCount} fetched, ${result.totalCount} total works in js/data.js (was ${result.existingCount}).`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
