import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

import { DECADES } from './lib/coverage.mjs';
import { mergeWorks } from './lib/mergeWorks.mjs';
import { applyEnrichment } from './lib/applyEnrichment.mjs';
import { mapWikidataFilmToWork } from './lib/mapWikidata.mjs';
import { loadSyncState, saveSyncState, getBucketProgress, recordBucketResult } from './lib/syncState.mjs';
import * as wikidata from './sources/wikidata.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REAL_DATA_FILE = join(__dirname, '..', 'js', 'data.js');
const REAL_ENRICHMENT_FILE = join(__dirname, '..', 'data', 'enrichment.json');
const REAL_SYNC_STATE_FILE = join(__dirname, '..', 'data', 'sync-state.json');

const TARGET_PER_DECADE_MOVIE = 40;  // ~40 x 13 decades ≈ 520 movies per full run
const BRAZIL_QID = 'Q155';
const RECENT_TARGET = 100;

export async function loadExistingWorks(dataFile) {
  if (!existsSync(dataFile)) return [];
  const mod = await import(`${pathToFileURL(dataFile).href}?t=${Date.now()}`);
  return mod.works || [];
}

export function loadEnrichment(enrichmentFile) {
  if (!existsSync(enrichmentFile)) return {};
  return JSON.parse(readFileSync(enrichmentFile, 'utf8'));
}

export function writeDataFile(dataFile, works) {
  const header = [
    '// AUTO-GENERATED by scripts/sync-data.mjs — do not hand-edit.',
    '// Run `npm run sync-data` to refresh, or `npm run sync-data -- --new` for an incremental update.',
    '// Optional hand-curation lives in data/enrichment.json, keyed by "<source.type>:<source.sourceId>".',
    '',
    '',
  ].join('\n');
  writeFileSync(dataFile, `${header}export const works = ${JSON.stringify(works, null, 2)};\n`, 'utf8');
}

// Runs one bucket's query against its saved checkpoint: skips entirely if the bucket
// is already known-exhausted (no network call at all), otherwise queries starting at
// the saved offset and advances/exhausts the checkpoint on success. A failed query
// (network/server error) leaves the checkpoint untouched, so the SAME offset is retried
// on the next run — nothing is skipped or double-counted because of a transient error.
export async function runBucket({ label, bucketKey, state, limit, query }) {
  const progress = getBucketProgress(state, bucketKey);
  if (progress.exhausted) {
    console.log(`[wikidata] ${label}: exhausted, skipping`);
    return { fresh: [], state };
  }
  try {
    const rows = await query(progress.offset);
    const nextState = recordBucketResult(state, bucketKey, rows.length, limit);
    const updated = nextState[bucketKey];
    console.log(`[wikidata] ${label}: +${rows.length} (offset now ${updated.offset}${updated.exhausted ? ', exhausted' : ''})`);
    return { fresh: rows, state: nextState };
  } catch (err) {
    console.warn(`[wikidata] ${label} failed at offset ${progress.offset}: ${err.message}`);
    return { fresh: [], state };
  }
}

async function fetchWikidataFull(apiKey, enrichmentMap) {
  const fresh = [];
  let state = loadSyncState(REAL_SYNC_STATE_FILE);

  for (const { start, end } of DECADES) {
    const filmResult = await runBucket({
      label: `film ${start}-${end}`,
      bucketKey: `wikidata:film:${start}-${end}`,
      state,
      limit: TARGET_PER_DECADE_MOVIE,
      query: (offset) => wikidata.queryFilms({ startYear: start, endYear: end, limit: TARGET_PER_DECADE_MOVIE, offset }),
    });
    state = filmResult.state;
    for (const row of filmResult.fresh) {
      fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
    }
    saveSyncState(REAL_SYNC_STATE_FILE, state);

    // Guarantee Brazilian representation explicitly per decade, rather than leaving it to chance —
    // this is a first-principles requirement of the product (Brazilian + international works),
    // not an incidental nice-to-have.
    const brazilResult = await runBucket({
      label: `Brazil film ${start}-${end}`,
      bucketKey: `wikidata:film:brazil:${start}-${end}`,
      state,
      limit: 10,
      query: (offset) => wikidata.queryFilms({ startYear: start, endYear: end, limit: 10, countryQid: BRAZIL_QID, offset }),
    });
    state = brazilResult.state;
    for (const row of brazilResult.fresh) {
      fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
    }
    saveSyncState(REAL_SYNC_STATE_FILE, state);
  }
  return fresh;
}

async function fetchWikidataRecent(apiKey, enrichmentMap) {
  const fresh = [];
  try {
    const filmRows = await wikidata.queryRecentFilms({ limit: RECENT_TARGET });
    for (const row of filmRows) {
      fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[wikidata] recent films failed: ${err.message}`);
  }

  // Guarantee Brazilian representation explicitly in incremental syncs too, mirroring
  // fetchWikidataFull — this is a first-principles product requirement, not something
  // that should only hold true right after a full resync.
  try {
    const brazilFilmRows = await wikidata.queryRecentFilms({ limit: 10, countryQid: BRAZIL_QID });
    for (const row of brazilFilmRows) {
      fresh.push(applyEnrichment(mapWikidataFilmToWork(row), enrichmentMap));
    }
  } catch (err) {
    console.warn(`[wikidata] recent Brazil films failed: ${err.message}`);
  }

  return fresh;
}

export async function runSync({ dataFile, enrichmentFile, fetchFresh, apiKey, incremental }) {
  const existing = await loadExistingWorks(dataFile);
  const enrichmentMap = loadEnrichment(enrichmentFile);
  const fresh = await fetchFresh(apiKey, enrichmentMap, incremental);
  const merged = mergeWorks(existing, fresh);
  writeDataFile(dataFile, merged);
  return { existingCount: existing.length, freshCount: fresh.length, totalCount: merged.length };
}

async function main() {
  const incremental = process.argv.includes('--new');
  const result = await runSync({
    dataFile: REAL_DATA_FILE,
    enrichmentFile: REAL_ENRICHMENT_FILE,
    fetchFresh: incremental ? fetchWikidataRecent : fetchWikidataFull,
    apiKey: null, // Wikidata needs no credential — kept as a parameter only because runSync's signature (Task 5 of the prior plan) still passes it through to fetchFresh
    incremental,
  });
  console.log(`Sync complete: ${result.freshCount} fetched, ${result.totalCount} total works in js/data.js (was ${result.existingCount}).`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
